apiVersion: "kubeflow.org/v1alpha2"
kind: "TFJob"
metadata:
  name: "mnist-simple-oss"
spec:
  tfReplicaSpecs:
    restartPolicy: Never
    template:
      spec:
        containers:
          - image: larryisdog/larry:5.0
            name: tensorflow
            command: ["python", "/var/tf_dist_mnist/mnist.py"]
            args:


