apiVersion: "kubeflow.org/v1alpha2"
kind: "TFJob"
metadata:
  name: "mnist-simple-oss"
spec:
  tfReplicaSpecs:
    restartPolicy: Never
    template:
      spec:
        containers:
          - image: houyadong/tf_example_mnist:1.0
            name: tensorflow
            command: ["python", "/var/tf_dist_mnist/mnist.py"]
            args:


